#!/usr/bin/env python2.7

import os
import cv2
import numpy as np
import sys, argparse

import sqlite3

#from NLMeans3D import *
from ParNLMeans3D import *
from ParNLMeans2D import *
from compareImages import *
from operator import itemgetter
import time

#Parser for input arguments
# Required = IN, OUT and ORI (Paths)
# Optional = H, P and W (NLMeans parameters)
parser = argparse.ArgumentParser(description='This is a script for NLMeans-3D-LBP.')
parser.add_argument('-in','--input', help='Input PATH with the input images (With Noise)',required=True)
parser.add_argument('-out','--output',help='Input PATH to save the output image (Denoised)', required=True)
parser.add_argument('-ori','--originals',help='Input PATH with the original images (Without Noise)', required=True)
parser.add_argument('-H','--filterStrength',help='Input the parameter H (Filter Strength)', type=int, required=False, default=3)
parser.add_argument('-p','--patch',help='Input the size of patch (Neighborhood size of centered voxel)', type=int,required=False, default=7)
parser.add_argument('-w','--window',help='Input the size of search window (Window size of centered voxel)', type=int,required=False, default=21)
parser.add_argument('-alg','--algorithm',help='Choose which algorithm will perform ()', choices=['nlm', 'nlmlbp', 'nlm3d', 'nlm3dlbp'], required=False)
parser.add_argument('-sig','--sigma',help='Value of Sigma (Noise std)', type=int, required=False, default=0)
parser.add_argument('-msb','--MSBValue',help='Value of Most Significant Bit', type=int, required=False, default=4)
parser.add_argument('-seq','--sequence', help='Sequence name',required=True)
parser.add_argument('-f','--folder', help='Input PATH with all sequence folders',required=True)
args = parser.parse_args()

#Convert arguments
pathNoiseFrames = args.input
pathDenoised = args.output
pathOri = args.originals
h = args.filterStrength
patchSize = args.patch
windowSize = args.window
valueSigma = args.sigma
valueMSB = args.MSBValue
seq = args.sequence

if valueSigma == 0:
    print ('\nH: %d, PatchSize: %d, WindowSearchSize: %d') % (h, patchSize, windowSize)
else:
    print ('\nNoise sigma: %d, H: %d, PatchSize: %d, WindowSearchSize: %d') % (valueSigma, h, patchSize, windowSize)

#Check if the Path for denoised images exist
#if don't, create!
if not os.path.exists(pathDenoised):
    os.makedirs(pathDenoised)

#Create list of all .PNG noise images
noiseFrameList = sorted(os.listdir(pathNoiseFrames))
noiseFrameList = [f for f in noiseFrameList if '.png' in f]

#Create list of all .PNG original images
oriFrameList = sorted(os.listdir(pathOri))
oriFrameList = [f for f in oriFrameList if '.png' in f]

# filters only ONE frame
n = (patchSize / 2) * 2 + (windowSize / 2) * 2 + 1
noiseFrameList = noiseFrameList[len(noiseFrameList) / 2 - n/2:len(noiseFrameList) / 2 + n/2 + 1]
oriFrameList = oriFrameList[len(oriFrameList) / 2 - n/2:len(oriFrameList) / 2 + n/2 + 1]
#noiseFrameList = noiseFrameList[0:n]
#oriFrameList = oriFrameList[0:n]

#Auxiliar
nFrames = len(noiseFrameList)
i = 0

#Create a NLMeans3D object
nlm = ParNLMeans3D(h = h, templateWindowSize = patchSize, searchWindowSize = windowSize, nMSB = valueMSB)

#Read noise frames
for f in noiseFrameList:
    #Read noise image
    auxPath = pathNoiseFrames + '/' + f
    gray = cv2.imread(auxPath, cv2.IMREAD_GRAYSCALE)
    gray = gray.astype(np.float64)#/255.0

    if i == 0:
        noiseVideo = np.zeros((nFrames, gray.shape[0], gray.shape[1]))

    #add frame to noiseVideo
    noiseVideo[i] = gray

    i += 1

i = 0
#Read original frames
for f in oriFrameList:
    #Read original image
    auxPath = pathOri + '/' + f
    gray = cv2.imread(auxPath, cv2.IMREAD_GRAYSCALE)
    gray = gray.astype(np.float64)#/255.0

    if i == 0:
        oriVideo = np.zeros((nFrames, gray.shape[0], gray.shape[1]))

    #add frame to noiseVideo
    oriVideo[i] = gray

    i += 1

#Get index denoised image
aux = patchSize / 2 + windowSize / 2

#Get start execution time
start_time = time.time()

#Run NLMeans2D OpenCV
outOpencv = cv2.fastNlMeansDenoising(np.uint8(noiseVideo[aux]),h=h,templateWindowSize=patchSize,searchWindowSize=windowSize)

#Run NLMeans2D denoised
print "Run NLMeans2D"
nlm2d = ParNLMeans2D(h,patchSize,windowSize)
outNLM2D, outNLM2DLBP = nlm2d.denoise(noiseVideo[aux])

#Run NLMeans3D denoise
print "\nRun NLMeans3D++"
nlm3d_viORI, nlm3d_viORI_texLBP, nlm3d_viORI_texLBPMSB, nlm3d_viORI_texLBPAdaptive,\
    nlm3d_viORI_texLBPMSBAdaptive, nlm3d_viMSB, nlm3d_viMSB_texLBP, \
    nlm3d_viMSB_texLBPMSB = nlm.denoise(noiseVideo)

print "\n"

#Get final execution time
total_time = time.time() - start_time

#Add PSNR and SSIM in list
rank = [("NLM2D",psnr(outNLM2D, oriVideo[aux]), ssim(outNLM2D, oriVideo[aux]),outNLM2D)];
rank.append(("NLM2D-LBP",psnr(outNLM2DLBP, oriVideo[aux]), ssim(outNLM2DLBP, oriVideo[aux]),outNLM2DLBP))
rank.append(("NLM2D-OpenCV",psnr(outOpencv.astype(np.float64), oriVideo[aux]), ssim(outOpencv.astype(np.float64), oriVideo[aux]),outOpencv))
rank.append(("NLM3D",psnr(nlm3d_viORI[aux], oriVideo[aux]), ssim(nlm3d_viORI[aux], oriVideo[aux]),nlm3d_viORI[aux]))
rank.append(("NLM3D_viORI_texLBP",psnr(nlm3d_viORI_texLBP[aux], oriVideo[aux]), ssim(nlm3d_viORI_texLBP[aux], oriVideo[aux]),nlm3d_viORI_texLBP[aux]))
rank.append(("NLM3D_viORI_texLBP-MSB",psnr(nlm3d_viORI_texLBPMSB[aux], oriVideo[aux]), ssim(nlm3d_viORI_texLBPMSB[aux], oriVideo[aux]),nlm3d_viORI_texLBPMSB[aux]))
rank.append(("NLM3D_viORI_texLBP_Adaptive",psnr(nlm3d_viORI_texLBPAdaptive[aux], oriVideo[aux]), ssim(nlm3d_viORI_texLBPAdaptive[aux], oriVideo[aux]),nlm3d_viORI_texLBPAdaptive[aux]))
rank.append(("NLM3D_viORI_texLBP-MSB_Adaptive",psnr(nlm3d_viORI_texLBPMSBAdaptive[aux], oriVideo[aux]), ssim(nlm3d_viORI_texLBPMSBAdaptive[aux], oriVideo[aux]),nlm3d_viORI_texLBPMSBAdaptive[aux]))
rank.append(("NLM3D_viMSB",psnr(nlm3d_viMSB[aux], oriVideo[aux]), ssim(nlm3d_viMSB[aux], oriVideo[aux]),nlm3d_viMSB[aux]))
rank.append(("NLM3D_viMSB_texLBP",psnr(nlm3d_viMSB_texLBP[aux], oriVideo[aux]), ssim(nlm3d_viMSB_texLBP[aux], oriVideo[aux]),nlm3d_viMSB_texLBP[aux]))
rank.append(("NLM3D_viMSB_texLBP-MSB",psnr(nlm3d_viMSB_texLBPMSB[aux], oriVideo[aux]), ssim(nlm3d_viMSB_texLBPMSB[aux], oriVideo[aux]),nlm3d_viMSB_texLBPMSB[aux]))

#Sort by higher SSIM
rank = sorted(rank, key=itemgetter(2),reverse=True)

#Save Results
text_file = open(pathDenoised + "results-2D.txt", "w")

text_file.write("\n---------------------------------------------\n")

text_file.write("Parameters: \n")
text_file.write("H: %d\n" % h)
text_file.write("PatchSize: %d\n" % patchSize)
text_file.write("WindowSize: %d\n" % windowSize)

text_file.write("\n---------------------------------------------\n")

text_file.write("Execution Time: %s \n\n" % time.strftime('%Hhrs %Mmin %Ssec', time.gmtime(total_time)))

text_file.write("---------------------------------------------\n")

text_file.write(("Image Noise - PSNR: %0.4f, SSIM %.4f \n") % \
            (psnr(noiseVideo[aux], oriVideo[aux]),\
             ssim(noiseVideo[aux], oriVideo[aux])))

text_file.write("\n---------------------------------------------\n")

#Save noise and original image
denoiseImagePath = pathDenoised + 'original.png'
cv2.imwrite(denoiseImagePath, oriVideo[aux])

denoiseImagePath = pathDenoised + 'noise.png'
cv2.imwrite(denoiseImagePath, noiseVideo[aux])

conn = sqlite3.connect(args.folder + '3d_denoising_results.db')
c = conn.cursor()

for i in range(0,len(rank)):
    # Insert a row of data
    t = [seq, valueSigma, rank[i][0], h, patchSize, windowSize, valueMSB, rank[i][1], rank[i][2]]
    c.execute("insert into results values (?,?,?,?,?,?,?,?,?)", t)

    #Writing result
    text_file.write(("%s - PSNR: %.4f, SSIM %.4f \n") % \
                        (rank[i][0], rank[i][1], rank[i][2]))
    #Writing image
    aux2 = rank[i][3].astype(np.uint8)
    denoiseImagePath = pathDenoised + rank[i][0] + '.png'
    cv2.imwrite(denoiseImagePath, aux2)

text_file.close()

# Save (commit) the changes and close DB connection
conn.commit()
conn.close()
